Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@ByBinPy 
ByBinPy
/
ISRPO6.1
Public
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
ISRPO6.1/.github/workflows/python-app.yml
@ByBinPy
ByBinPy Update python-app.yml
Latest commit 86484c9 13 minutes ago
 History
 1 contributor
28 lines (28 sloc)  753 Bytes

name: Run tests on any Push event
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  test_build:
    runs-on: [ubuntu-latest]
    steps:
    
      - uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Initial 
        run: pip freeze > requirements.txt
      - name: Install 
        run: pip install -r requirements.txt
      - name: Add Reporter
        run: pip install coverage
      - name: Run tests
        run: coverage run TestCalc.py
      - name: Tests report
        run: coverage report
