name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
          cache: pip
          cache-dependency-path: 'requirements/*.pip'
          
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --require-hashes -r requirements/tox.pip
          
      - name: "Install depes"
        run: |
          set -xe
          python -VV
          python -m site
       
          python Calculator/Test_programm_calculator/Calculator_test.py
          
      - name: "Install "
        run: |
          set -xe
          python -VV
          python -m site
       
          python Calculator/calculator_in/calculator.py
          
      - name: "Ins"
        run: |
          set -xe
          python -VV
          python -m site
       
          python Calculator/main.py
          
          
          
      - name: Run unittest
        run: coverage run Calculator/Test_programm_calculator/Calculator_test.py
      - name: Tests report
        run: coverage report
